version: '3'
services:
    frontend:
        restart: unless-stopped
        image: staticfloat/nginx-certbot
        ports:
            - 80:80
            - 443:443
        environment:
            CERTBOT_EMAIL: pratikaher88@gmail.com
        volumes:
          - ./data/nginx:/etc/nginx/user.conf.d:ro
          - letsencrypt:/etc/letsencrypt
volumes:
    letsencrypt:

networks:
    default:
        name: parent-network
          